#!/bin/bash

read -p "Enter a number: " NUM1
read -p "Enter a another number: " NUM2

SUM=`expr ${NUM1} + ${NUM2}`
SUB=`expr ${NUM1} - ${NUM2}`
MUL=`expr ${NUM1} \* ${NUM2}`
DIV=`expr ${NUM1} / ${NUM2}`
MOD=`expr ${NUM1} % ${NUM2}`

echo "${NUM1} + ${NUM2} = ${SUM}" 
echo "${NUM1} - ${NUM2} = ${SUB}" 
echo "${NUM1} \* ${NUM2} = ${MUL}" 
echo "${NUM1} / ${NUM2} = ${DIV}" 
echo "${NUM1} % ${NUM2} = ${MOD}" 
